=== micronaut-projects/micronaut-guides/guide_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "minimumJavaVersion": {
            "type": "integer"
        },
        "prerequesites": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "clouds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skipGradleTests": {
            "type": "boolean"
        },
        "intro": {
            "type": "string"
        },
        "skipMavenTests": {
            "type": "boolean"
        },
        "features": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "publicationDate": {
            "type": "string"
        },
        "asciidoctor": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "buildTools": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "testFramework": {
            "type": "string"
        },
        "zipIncludes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "slug": {
            "type": "string"
        },
        "publish": {
            "type": "boolean"
        },
        "title": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "maximumJavaVersion": {
            "type": "integer"
        },
        "base": {
            "type": "string"
        },
        "env": {
            "type": "object",
            "properties": {
                "AWS_SECRET_ACCESS_KEY": {
                    "type": "string"
                },
                "AWS_REGION": {
                    "type": "string"
                },
                "AWS_ACCESS_KEY_ID": {
                    "type": "string"
                }
            }
        },
        "apps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "invisibleFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "kotlinFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "validateLicense": {
                        "type": "boolean"
                    },
                    "testFramework": {
                        "type": "string"
                    },
                    "javaFeatures": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "framework": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "features": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "packageName": {
                        "type": "string"
                    },
                    "excludeTest": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applicationType": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== micronaut-projects/micronaut-guides/guides/micronaut-kotlin-extension-fns/metadata.json
{
  "asciidoctor": "micronaut-kotlin-extension-fns.adoc",
  "slug": "micronaut-kotlin-extension-fns",
  "title": "Using Kotlin Extension Functions in Micronaut",
  "intro": "Take a tour of the extension functions in Micronaut and learn to write your own",
  "authors": ["Will Buck"],
  "languages": ["kotlin"],
  "apps": [
    {
      "name": "default",
      "features": ["graalvm", "kotlin-extension-functions"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-security-basicauth/metadata.json
{
  "title": "Micronaut Basic Auth",
  "intro": "Learn how to secure a Micronaut application using 'Basic' HTTP Authentication Scheme.",
  "features": ["security", "graalvm"],
  "authors": ["Sergio del Amo"],
  "tags": ["basic-auth", "security", "graal"],
  "categories": ["Micronaut Security"],
  "publicationDate": "2018-05-24",
  "languages": ["JAVA", "GROOVY", "KOTLIN", "PYTHON"],
  "apps": [
    {
      "name": "default",
      "features": ["security"],
      "javaFeatures": ["graalvm"],
      "kotlinFeatures": ["graalvm"]
    }
  ]
}

=== micronaut-projects/micronaut-guides/guides/micronaut-data-access-jpa-hibernate/metadata.json
{
  "asciidoctor": "micronaut-data-access-jpa-hibernate.adoc",
  "slug": "micronaut-data-access-jpa-hibernate",
  "title": "Access a database with JPA and Hibernate",
  "intro": "Learn how to access a database with JPA and Hibernate using Micronaut.",
  "authors": ["Sergio del Amo"],
  "languages": ["java"],
  "apps": [
    {
      "name": "default",
      "features": ["graalvm", "hibernate-jpa", "data-jpa"]
    }
  ]
}
